### ISSUE TITLE
Permissions not inherited for users in a private site

### ISSUE THREAD

**Issue by rusuandrei** [AlfrescoTestAutomation/dataprep#18]
Using dataprep create a private site and add users with roles to site: SiteContributor, SiteCollaborator, SiteManager, Site Consumer. But their permissions won't be inherited ("permissions":{"inherited":false,"roles":[]). User with contributor role will not see in document library the files created by other users.

**Comment by bogdanbocancea** [comment]
closed due to bug **https://issues.alfresco.com/jira/browse/ACE-4614**
